### ISSUE TITLE
Merge this repo with Awesome Polymer by Granze

### ISSUE THREAD

**Issue by web-padawan** [StartPolymer/awesome-polymer#1]
There is another [Awesome Polymer](https://github.com/Granze/awesome-polymer) repo, which is more starred than this one, and also included to the official awesome list.

Now I'm a bit confused, wondering about where should I send my PR's?
It would be nice if you guys could create a single reliable Awesome Polymer list.

Not sure about how should it be reached, maybe transferring ownership, or something else.

@JosefJezek @Granze WDYT?

**Comment by Granze** [comment]
Well, there is no reason to have two lists. I'm open to discussion on how to merge them.
As @web-padawan says, mine is more starred and is also older than this one.
Btw, I suggest to always do a search before starting a project to check if something similar already exist.

Let my know your thoughts @JosefJezek :)

**Comment by JosefJezek** [comment]
@Granze Please merge your list with this list. Thank you.
